import sys
import numpy as np
import json
import os
import pickle


import pickle
from pathlib import Path
from sklearn import metrics
from scipy.stats import norm

mode = 'random_sampling'

def simulated_tests(real_magnitude, cross_idx, N_train):
    Nfuncts = 1000
    d = 14
    
    # print('Read random functions variances')
    with open('../deep_learning/result_saved/' + mode + '/Simulation/variances_{0}'.format(Nfuncts), 'rb') as f:
        variances = pickle.load(f)
    with open('../deep_learning/result_saved/' + mode + '/Simulation/absolute_value_{0}'.format(Nfuncts), 'rb') as f:
        absolute_value = pickle.load(f)

    Cov = np.diag(variances) 

    simulate_magnitude = np.mean(absolute_value)
    N = 1000       
        
    # print('Read samples from random functions')
    with open('../deep_learning/result_saved/' + mode + '/Simulation/samples_gradient_func_test_{0}'.format(N), 'rb') as f:
        samples = pickle.load(f)
    with open('../deep_learning/result_saved/' + mode + '/Simulation/samples_interaction_func_test_{0}'.format(N), 'rb') as f:
        interaction_samples = pickle.load(f)                  

    # Compute the test statistics. How large is it?
    
    estimation_rate = (N_train / np.log(N_train)) ** ((d + 1) / (2 * (2 * d + 1)))
    
    ### First, calculate the 
    logdirs = ['../deep_learning/output_RF/' + mode \
               + '/Train_fold_'+str(k)+'/fullnew46591640.950.00.0010.01Factor_sharpeTest'+str(cross_idx) for k in range(1,9)]
    gradients_list = []
    for logdir in logdirs:
        gradients_list.append(np.load(os.path.join(logdir, 'ave_absolute_gradient_square.npy')))        
    gradients = np.array(gradients_list).mean(axis=0)
    
    #### Next, calculate the gradient generated by the model.
    plot_list  = ['ages','flow','exp_ratio','tna','turnover','Family_TNA','fund_no',\
                      'Family_r12_2','Family_flow','Family_age','F_ST_Rev','F_r2_1','F_r12_2']
    interaction_real = np.zeros((len(plot_list)))
    v_list = []        
    for i, name_x in enumerate(plot_list):  
        v_new = np.load('../deep_learning/result_saved/' + \
                        mode + '/Interaction/ave_mean'+str(cross_idx)+ str(name_x)+'sentiment14.npy') 
        interaction_real[i] = (v_new[4,-1] - v_new[4,0]) - (v_new[0,-1] - v_new[0,0])  
    
    test_stats = samples* real_magnitude**2/(simulate_magnitude**2 * (estimation_rate**2))
    interaction_stats =  interaction_samples * real_magnitude/ (simulate_magnitude* estimation_rate)
    
    return gradients, interaction_real, test_stats, interaction_stats, plot_list


def average_over_fold(samples, interaction_samples, gradients, interaction_real):
    
    q_lower = np.percentile(samples, 90, axis = 0)
    q = np.percentile(samples, 95, axis = 0)
    q_higher = np.percentile(samples, 99, axis = 0)
    
    
    q_interaction_lower = np.percentile(interaction_samples, 90, axis = 0)
    q_interaction = np.percentile(interaction_samples, 95, axis = 0)
    q_higher_interaction = np.percentile(interaction_samples, 99, axis = 0)

    return (gradients> q_lower).astype(int), (gradients>q).astype(int), (gradients>q_higher).astype(int), (interaction_real>q_interaction).astype(int), (interaction_real>q_interaction).astype(int), (interaction_real> q_higher_interaction).astype(int)


   

def print_significance(sig_90, sig_95, sig_99, sig_inter_90, sig_inter_95, sig_inter_99, gradients, interactions, plot_list, print_order, filename):
    N = len(sig_90)
    
    for idx in range(N):
        i = print_order[idx]
        string = '\_'.join(plot_list[i].split('_'))
        if sig_99[i]:
            string+='&%.2f***'%(np.sqrt(gradients[i])*100)
        elif sig_95[i]:
            string+='&%.2f**'%(np.sqrt(gradients[i])*100)
        elif sig_90[i]:
            string+= '&%.2f*'%(np.sqrt(gradients[i])*100)
        else:
            string+= '&%.2f'%(np.sqrt(gradients[i])*100)
        
        if i<N-1:
            if sig_inter_99[i]:
                string+= '&%.2f***'%(interactions[i]*100)
            elif sig_inter_95[i]:
                string+= '&%.2f**'%(interactions[i]*100)
            elif sig_inter_90[i]:
                string+= '&%.2f*'%(interactions[i]*100)
            else:
                string+= '&%.2f'%(interactions[i]*100)
        
        string+='\\\\\n'
            
        filename.write(string)
    
    
if __name__ == "__main__":

    subset = range(46, 60)
    real_magnitude_lists = []
    
    gradients_list, interaction_list, simu_grad_list, simu_interaction_list = [], [], [], []
    
    
    for cross_idx in range(3):
        
        data_real = np.load('../deep_learning/result_saved/' + mode + '/Simulation/real_magnitude_' + str(cross_idx) + '.npz')
        
        N_train = data_real["N_train"]
        real_magnitude = data_real["real_magnitude"]
    
        gradients, interaction_real, simu_grad, simu_interaction, plot_list = simulated_tests(real_magnitude, cross_idx, N_train)
        
        gradients_list.append(gradients), interaction_list.append(interaction_real), simu_grad_list.append(simu_grad), simu_interaction_list.append(simu_interaction) 
        
    plot_list+=['sentiment']
    
    avg_gradient, avg_interaction, avg_grad_stats, avg_interaction_stats = np.mean(gradients_list, axis = 0), np.mean(interaction_list, axis = 0), np.mean(simu_grad_list, axis = 0), np.mean(simu_interaction_list, axis = 0)
    
    sig_gradient_90, sig_gradient_95, sig_gradient_99, sig_interaction_90, sig_interaction_95, sig_interaction_99 = average_over_fold(np.abs(avg_grad_stats), np.abs(avg_interaction_stats), np.abs(avg_gradient), np.abs(avg_interaction))

    print_order = np.argsort(avg_gradient)[::-1]    
#    print (">>>>>>>>>>>>>>>>>>>>>>")
#    print ("Generate output for Table 6a (Random sampling case)")
#    print (">>>>>>>>>>>>>>>>>>>>>>")
    text_file = open("tables/Table6a.txt", "wt")
    print_significance(sig_gradient_90, sig_gradient_95, sig_gradient_99, sig_interaction_90, sig_interaction_95, sig_interaction_99, avg_gradient, avg_interaction, plot_list, print_order, text_file)
    text_file.close()
    
    





